function(MAKEHEADERS OUTLIST LIST)
   SET(TMP_LIST)
   foreach (_current_FILE ${LIST})
     STRING(REGEX REPLACE "^(.*)cxx" "\\1h" TMP ${_current_FILE})
     SET (TMP_LIST ${TMP_LIST} ${TMP})
   endforeach (_current_FILE ${ARGN})
   SET (${OUTLIST} ${TMP_LIST} PARENT_SCOPE)
endfunction ()
function(GENERATE_BASH)
	file( WRITE ${CMAKE_BINARY_DIR}/config.sh "#!/bin/bash\n" )
	file( APPEND ${CMAKE_BINARY_DIR}/config.sh "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CMAKE_INSTALL_PREFIX}/lib\n")
	file( APPEND ${CMAKE_BINARY_DIR}/config.sh "export PATH=$PATH:${CMAKE_INSTALL_PREFIX}/bin\n")
	file( APPEND ${CMAKE_BINARY_DIR}/config.sh "export UBOOT=${CMAKE_INSTALL_PREFIX}/data\n")
	if(DEFINED URQMD_PATH)
		file( APPEND ${CMAKE_BINARY_DIR}/config.sh "export URQMD=${URQMD_PATH}\n")
	endif()
endfunction()

